development:
  adapter: postgresql
  host: localhost
  database: todo_development

test:
  adapter: postgresql
  host: localhost
  database: todo_test

travisci:
  adapter: postgresql
  host: localhost
  database: todo_test
  username: postgres